### ISSUE TITLE
没法在软件内，进行页面的跳转

### ISSUE THREAD

**Issue by xuexuguang** [lpdswing/chatgpt#10]
比如我的入口是个ai的导航页，我需要启动定位到导航页，然后点击页面上的链接，跳转到别的地方，但是好像是没有反应呢

**Comment by lpdswing** [comment]
网址是啥,我试试

**Comment by xuexuguang** [comment]
https://lj.lbbai.com/#url=lbbdh



比如这个，好像是点击网址之后又进行了重定向了。所以跳转不过去了
