### ISSUE TITLE
用api有时会回去一直在思考,建议加个停止按钮,对话条数多了也会卡住一直在思考,再加个导出历史记录为图片的功能

### ISSUE THREAD

**Issue by lantern9** [lpdswing/chatgpt#3]
用api有时会回去一直在思考,建议加个停止按钮,对话条数多了也会卡住一直在思考,再加个导出历史记录为图片的功能

**Comment by lpdswing** [comment]
一直思考是chatchat服务的问题, 这个没有好的办法, 最好切换其他免费镜像, 导出图片可以用js脚本, 后序考虑实现
