### ISSUE TITLE
侧栏模式优化

### ISSUE THREAD

**Issue by playingapi** [lpdswing/chatgpt#5]
侧栏模式隐藏菜单栏和标题栏， 显示托盘图标 ,  记住侧栏的位置和大小   增加快捷键快速打开侧栏

**Comment by lpdswing** [comment]
现在用的这个框架暂不支持系统托盘, 0.6.0已经支持快捷键切换侧边栏

**Comment by playingapi** [comment]
希望侧栏和窗口都支持无边框模式

**Comment by lpdswing** [comment]
无边框会有无法移动窗口的问题
