### ISSUE TITLE
保存用户登录状态

### ISSUE THREAD

**Issue by playingapi** [lpdswing/chatgpt#8]
没找到该app保存的数据(user data), 希望可以导出浏览器的user data ，  之后方便恢复登录的所有网站 ， 不用重新登录，

能实现 user data的切换最好,  比如可以多开2个应用  这2个应用加载自己不同的数据,  第一个用作ai模型, 第2个用作模拟手机上网?

**Comment by lpdswing** [comment]
现在是可以存储登录状态的, webview是会保留登录信息的和浏览器一样

**Comment by playingapi** [comment]
我是指换了一台新电脑 然后把以前的登录状态可以迁移过去  不用再次登录

**Comment by lpdswing** [comment]
换电脑做不到
